// Mock data to replace database calls and avoid RLS issues
export const mockPortfolioItems = [
  {
    id: "1",
    title: "Luxury Watch Box",
    slug: "luxury-watch-box",
    description: "Premium packaging solution for high-end timepieces featuring velvet interior and gold foil stamping.",
    client_name: "Luxury Timepieces Co.",
    project_date: "2024-01-15",
    category_id: "luxury-boxes",
    featured_image: null,
    status: "published",
    language: "en",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
    created_by: "admin",
    categories: { name: "Luxury Boxes", slug: "luxury-boxes" },
    portfolio_features: [
      { feature_name: "Gold Foil Stamping" },
      { feature_name: "Velvet Interior" },
      { feature_name: "Magnetic Closure" },
      { feature_name: "Premium Materials" },
    ],
    portfolio_images: [],
    media: { file_path: "luxury-watch-box.jpg", alt_text: "Luxury watch packaging box" },
  },
  {
    id: "2",
    title: "Premium Trading Cards",
    slug: "premium-trading-cards",
    description: "High-quality trading card printing with holographic foil and specialty finishes.",
    client_name: "Gaming Studio X",
    project_date: "2024-01-10",
    category_id: "trading-cards",
    featured_image: null,
    status: "published",
    language: "en",
    created_at: "2024-01-10T10:00:00Z",
    updated_at: "2024-01-10T10:00:00Z",
    created_by: "admin",
    categories: { name: "Trading Cards", slug: "trading-cards" },
    portfolio_features: [
      { feature_name: "Holographic Foil" },
      { feature_name: "UV Coating" },
      { feature_name: "Premium Card Stock" },
      { feature_name: "Custom Design" },
    ],
    portfolio_images: [],
    media: { file_path: "trading-cards.jpg", alt_text: "Premium trading cards with holographic finish" },
  },
  {
    id: "3",
    title: "Custom Jewelry Box",
    slug: "custom-jewelry-box",
    description: "Bespoke jewelry packaging with embossed logo and satin lining.",
    client_name: "Diamond Boutique",
    project_date: "2024-01-05",
    category_id: "luxury-boxes",
    featured_image: null,
    status: "published",
    language: "en",
    created_at: "2024-01-05T10:00:00Z",
    updated_at: "2024-01-05T10:00:00Z",
    created_by: "admin",
    categories: { name: "Luxury Boxes", slug: "luxury-boxes" },
    portfolio_features: [
      { feature_name: "Embossed Logo" },
      { feature_name: "Satin Lining" },
      { feature_name: "Custom Compartments" },
      { feature_name: "Luxury Finish" },
    ],
    portfolio_images: [],
    media: { file_path: "jewelry-box.jpg", alt_text: "Custom jewelry packaging box" },
  },
  {
    id: "4",
    title: "Perfume Gift Set",
    slug: "perfume-gift-set",
    description: "Elegant packaging for luxury fragrance collections with custom inserts.",
    client_name: "Fragrance House",
    project_date: "2023-12-20",
    category_id: "luxury-boxes",
    featured_image: null,
    status: "published",
    language: "en",
    created_at: "2023-12-20T10:00:00Z",
    updated_at: "2023-12-20T10:00:00Z",
    created_by: "admin",
    categories: { name: "Luxury Boxes", slug: "luxury-boxes" },
    portfolio_features: [
      { feature_name: "Custom Inserts" },
      { feature_name: "Soft Touch Coating" },
      { feature_name: "Ribbon Details" },
      { feature_name: "Premium Cardboard" },
    ],
    portfolio_images: [],
    media: { file_path: "perfume-box.jpg", alt_text: "Luxury perfume gift set packaging" },
  },
  {
    id: "5",
    title: "Collectible Card Game",
    slug: "collectible-card-game",
    description: "Complete card game packaging including booster packs and starter decks.",
    client_name: "Collectors United",
    project_date: "2023-12-15",
    category_id: "trading-cards",
    featured_image: null,
    status: "published",
    language: "en",
    created_at: "2023-12-15T10:00:00Z",
    updated_at: "2023-12-15T10:00:00Z",
    created_by: "admin",
    categories: { name: "Trading Cards", slug: "trading-cards" },
    portfolio_features: [
      { feature_name: "Foil Stamping" },
      { feature_name: "Spot UV" },
      { feature_name: "Die Cut Windows" },
      { feature_name: "Matte Lamination" },
    ],
    portfolio_images: [],
    media: { file_path: "card-game.jpg", alt_text: "Collectible card game packaging" },
  },
  {
    id: "6",
    title: "Whiskey Bottle Box",
    slug: "whiskey-bottle-box",
    description: "Premium packaging for limited edition whiskey bottles with custom foam inserts.",
    client_name: "Distillery Premium",
    project_date: "2023-12-10",
    category_id: "specialty-finishes",
    featured_image: null,
    status: "published",
    language: "en",
    created_at: "2023-12-10T10:00:00Z",
    updated_at: "2023-12-10T10:00:00Z",
    created_by: "admin",
    categories: { name: "Specialty Finishes", slug: "specialty-finishes" },
    portfolio_features: [
      { feature_name: "Custom Foam Insert" },
      { feature_name: "Textured Paper" },
      { feature_name: "Hot Stamping" },
      { feature_name: "Rigid Construction" },
    ],
    portfolio_images: [],
    media: { file_path: "whiskey-box.jpg", alt_text: "Premium whiskey bottle packaging" },
  },
]

export const mockBlogPosts = [
  {
    id: "1",
    title: "The Future of Sustainable Packaging",
    slug: "future-sustainable-packaging",
    excerpt: "Explore how eco-friendly materials and processes are shaping the luxury packaging industry.",
    content:
      "<h2>Introduction</h2><p>Sustainability is becoming increasingly important in the packaging industry...</p>",
    status: "published",
    language: "en",
    author_id: "admin",
    published_at: "2024-01-15T10:00:00Z",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
    view_count: 1247,
    seo_title: "Sustainable Packaging Trends 2024 | DIW Packaging",
    seo_description: "Discover the latest trends in sustainable luxury packaging and eco-friendly solutions.",
    seo_keywords: "sustainable packaging, eco-friendly, luxury packaging",
    featured_image: null,
    profiles: { full_name: "Maria Novak", avatar_url: null },
    media: { file_path: "sustainable-packaging.jpg", alt_text: "Sustainable packaging materials" },
    blog_post_tags: [
      { tags: { name: "Sustainability", slug: "sustainability" } },
      { tags: { name: "Innovation", slug: "innovation" } },
    ],
  },
  {
    id: "2",
    title: "Trading Card Design Trends 2024",
    slug: "trading-card-design-trends-2024",
    excerpt: "Discover the latest trends in trading card design, from holographic effects to interactive elements.",
    content: "<h2>Current Trends</h2><p>The trading card industry is experiencing a renaissance...</p>",
    status: "published",
    language: "en",
    author_id: "admin",
    published_at: "2024-01-10T10:00:00Z",
    created_at: "2024-01-10T10:00:00Z",
    updated_at: "2024-01-10T10:00:00Z",
    view_count: 892,
    seo_title: "Trading Card Design Trends 2024 | DIW Packaging",
    seo_description: "Explore the latest trading card design trends and printing innovations.",
    seo_keywords: "trading cards, design trends, holographic, printing",
    featured_image: null,
    profiles: { full_name: "Peter Koval", avatar_url: null },
    media: { file_path: "trading-card-trends.jpg", alt_text: "Modern trading card designs" },
    blog_post_tags: [
      { tags: { name: "Design", slug: "design" } },
      { tags: { name: "Trading Cards", slug: "trading-cards" } },
    ],
  },
  {
    id: "3",
    title: "The Psychology of Luxury Packaging",
    slug: "psychology-luxury-packaging",
    excerpt: "Understanding how premium packaging influences consumer behavior and brand perception.",
    content: "<h2>The Power of First Impressions</h2><p>Luxury packaging creates an emotional connection...</p>",
    status: "published",
    language: "en",
    author_id: "admin",
    published_at: "2024-01-05T10:00:00Z",
    created_at: "2024-01-05T10:00:00Z",
    updated_at: "2024-01-05T10:00:00Z",
    view_count: 1156,
    seo_title: "Psychology of Luxury Packaging | DIW Packaging",
    seo_description: "Learn how premium packaging influences consumer behavior and brand perception.",
    seo_keywords: "luxury packaging, psychology, consumer behavior, branding",
    featured_image: null,
    profiles: { full_name: "Maria Novak", avatar_url: null },
    media: { file_path: "luxury-psychology.jpg", alt_text: "Luxury packaging psychology" },
    blog_post_tags: [
      { tags: { name: "Psychology", slug: "psychology" } },
      { tags: { name: "Luxury", slug: "luxury" } },
    ],
  },
]

export const mockCategories = [
  { id: "all", name: "All Projects", slug: "all" },
  { id: "luxury-boxes", name: "Luxury Boxes", slug: "luxury-boxes" },
  { id: "trading-cards", name: "Trading Cards", slug: "trading-cards" },
  { id: "specialty-finishes", name: "Specialty Finishes", slug: "specialty-finishes" },
  { id: "custom-packaging", name: "Custom Packaging", slug: "custom-packaging" },
]
